name: makeup_payment_app
description: Taller bases de datos locales - App de pago cosméticos

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true